# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9571ea6d74a7686172201b0a2cc21f502dc6bacc8a5546a5bc837545225d98340688c9635b070ac5306d81c8b24245a072bbc2dc53b677b6944223ca1539cc

test:
  secret_key_base: ec9b47dc320b28b573d44c514cb8cdab493ef8c71f662bccb2d7e4d7e40030af2125821826b81ae9f005deb02d6e05178229e4143ff3193de0ae625c05cbcb4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
